# permissions for end users to view lezaoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lezao-viewer-role
rules:
- apiGroups:
  - cloudproduce.nancal.com
  resources:
  - lezaoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudproduce.nancal.com
  resources:
  - lezaoes/status
  verbs:
  - get
